/*
 * DddTacticalPatternsDemo.java
 *
 * Demonstrates:
 *   1. A Value Object -- Money as a record with a compact constructor enforcing an
 *      invariant (non-negative), immutable, equal-by-value.
 *   2. An Entity -- Customer, defined by a continuous identity (CustomerId), with
 *      behavior living ON the entity rather than in a separate anemic "service".
 *   3. An Aggregate Root -- Order, enforcing invariants across its child entities
 *      (OrderLine) and only ever mutated through its own methods.
 *   4. A Repository interface -- defined per aggregate root, with a simple in-memory
 *      implementation (kept out of the domain, as files 01/02 would prescribe).
 *   5. A Domain Event -- OrderSubmitted, an immutable past-tense record, raised as a
 *      side effect of a state change and collected for later publication.
 *
 * Covers Theory chapter:
 *   10) Java/02) Object-Oriented Programming in Java/Theory/12 Domain-Driven Design Tactical Patterns in Java.md
 *
 * Compile:  javac 04_DddTacticalPatternsDemo.java
 * Run:      java DddTacticalPatternsDemo
 */

import java.math.BigDecimal;
import java.time.Instant;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

// =============================================================================
// VALUE OBJECT -- Money. Defined entirely by its attributes, immutable, no identity.
// A record is an excellent fit: equals()/hashCode()/toString() are generated by value.
// =============================================================================

record Money(BigDecimal amount) {
    Money {                                        // compact constructor -- enforces the invariant on EVERY instance
        Objects.requireNonNull(amount, "amount is required");
        if (amount.signum() < 0) throw new IllegalArgumentException("Money cannot be negative");
    }

    static Money zero() { return new Money(BigDecimal.ZERO); }

    Money add(Money other) {                        // "changing" money returns a NEW Money -- never mutates
        return new Money(this.amount.add(other.amount));
    }

    Money multipliedBy(int quantity) {
        return new Money(this.amount.multiply(BigDecimal.valueOf(quantity)));
    }
}

// =============================================================================
// ENTITY -- Customer. Defined by a continuous identity (CustomerId), not by attribute
// values. Behavior (changeEmail) lives ON the entity, not in a separate service class.
// =============================================================================

record CustomerId(String value) { }

class Customer {
    private final CustomerId id;         // identity -- immutable once assigned, never changes
    private String name;                  // attribute -- can change without changing WHICH customer this is
    private String email;

    Customer(CustomerId id, String name, String email) {
        this.id = id;
        this.name = name;
        this.email = email;
    }

    void changeEmail(String newEmail) {      // business rule lives ON the entity, not in a "CustomerService"
        if (newEmail == null || !newEmail.contains("@"))
            throw new IllegalArgumentException("Invalid email address: " + newEmail);
        this.email = newEmail;
    }

    CustomerId id() { return id; }
    String name() { return name; }
    String email() { return email; }

    @Override
    public boolean equals(Object o) {         // equality is by IDENTITY, not by attribute values
        if (this == o) return true;
        if (!(o instanceof Customer other)) return false;
        return id.equals(other.id);             // note: name/email are NOT part of equality
    }

    @Override
    public int hashCode() { return id.hashCode(); }
}

// =============================================================================
// DOMAIN EVENT -- OrderSubmitted. Immutable, past-tense, carries exactly the facts
// other code needs to react to, without the Order knowing who (if anyone) is listening.
// =============================================================================

record OrderSubmitted(String orderId, CustomerId customerId, Money total, Instant occurredAt) { }

// =============================================================================
// AGGREGATE ROOT -- Order (root) + OrderLine (internal entity), treated as ONE
// consistency boundary. OrderLine is never exposed as a mutable reference outward --
// every mutation is routed through Order's own methods, which enforce the invariants.
// =============================================================================

enum OrderStatus { DRAFT, SUBMITTED }

/** Internal entity -- never referenced directly from outside the Order aggregate. */
class OrderLine {
    private final String productSku;
    private final int quantity;
    private final Money unitPrice;

    OrderLine(String productSku, int quantity, Money unitPrice) {
        if (quantity <= 0) throw new IllegalArgumentException("Quantity must be positive");
        this.productSku = productSku;
        this.quantity = quantity;
        this.unitPrice = unitPrice;
    }

    Money lineTotal() { return unitPrice.multipliedBy(quantity); }
    String productSku() { return productSku; }
    int quantity() { return quantity; }
}

/** Aggregate root -- the ONLY entry point external code may hold a reference to. */
class Order {
    private static final int MAX_LINES = 5;   // an invariant the ROOT enforces for the WHOLE aggregate

    private final String id;
    private final CustomerId customerId;
    private final List<OrderLine> lines = new ArrayList<>();
    private OrderStatus status = OrderStatus.DRAFT;
    private final List<Object> pendingEvents = new ArrayList<>();   // raised events, not yet published

    Order(String id, CustomerId customerId) {
        this.id = id;
        this.customerId = customerId;
    }

    void addLine(String productSku, int quantity, Money unitPrice) {
        if (status != OrderStatus.DRAFT)
            throw new IllegalStateException("Cannot modify an order that is no longer a draft");
        if (lines.size() >= MAX_LINES)
            throw new IllegalStateException("Order cannot exceed " + MAX_LINES + " lines");
        lines.add(new OrderLine(productSku, quantity, unitPrice));      // internal entity created HERE, by the root
    }

    void submit() {
        if (lines.isEmpty()) throw new IllegalStateException("Cannot submit an order with no lines");
        if (status != OrderStatus.DRAFT) throw new IllegalStateException("Order has already been submitted");
        this.status = OrderStatus.SUBMITTED;
        pendingEvents.add(new OrderSubmitted(id, customerId, total(), Instant.now()));   // recorded, not dispatched
    }

    Money total() {                                  // aggregate-wide computation belongs on the root
        Money sum = Money.zero();
        for (OrderLine line : lines) sum = sum.add(line.lineTotal());
        return sum;
    }

    List<Object> pullPendingEvents() {                 // application layer collects & publishes these after saving
        List<Object> events = List.copyOf(pendingEvents);
        pendingEvents.clear();
        return events;
    }

    String id() { return id; }
    CustomerId customerId() { return customerId; }
    OrderStatus status() { return status; }
    List<OrderLine> lines() { return List.copyOf(lines); }   // read-only VIEW out -- never the live mutable list
}

// =============================================================================
// REPOSITORY -- defined PER AGGREGATE ROOT (Order only, never a separate
// OrderLineRepository, since OrderLine has no independent existence outside Order).
// =============================================================================

interface OrderRepository {
    void save(Order order);
    Optional<Order> findById(String orderId);
}

/** Simple in-memory implementation -- kept outside the domain model itself. */
class InMemoryOrderRepository implements OrderRepository {
    private final Map<String, Order> store = new HashMap<>();

    @Override
    public void save(Order order) {
        store.put(order.id(), order);
    }

    @Override
    public Optional<Order> findById(String orderId) {
        return Optional.ofNullable(store.get(orderId));
    }
}

// =============================================================================
// Main class
// =============================================================================

public class DddTacticalPatternsDemo {

    private static void printSection(String title) {
        System.out.println();
        System.out.println("=".repeat(78));
        System.out.println(title);
        System.out.println("=".repeat(78));
    }

    // -------------------------------------------------------------------------
    // Demo 1: Value Object -- Money is equal by value, immutable, invariant-enforced.
    // -------------------------------------------------------------------------
    private static void demoValueObject() {
        printSection("1) Value Object -- Money is immutable and equal by VALUE, not identity");

        Money price = new Money(BigDecimal.valueOf(49.99));
        Money samePrice = new Money(BigDecimal.valueOf(49.99));
        System.out.println("  price.equals(samePrice) = " + price.equals(samePrice));
        assert price.equals(samePrice) : "two Money instances with equal amounts must be equal";

        Money combined = price.add(new Money(BigDecimal.valueOf(0.01)));
        System.out.println("  price.add(0.01) = " + combined.amount());
        assert !price.equals(combined) : "adding money must return a NEW instance, not mutate the original";

        try {
            new Money(BigDecimal.valueOf(-5));
        } catch (IllegalArgumentException e) {
            System.out.println("  Caught expected exception: " + e.getMessage());
        }
    }

    // -------------------------------------------------------------------------
    // Demo 2: Entity -- Customer identity survives attribute changes.
    // -------------------------------------------------------------------------
    private static void demoEntity() {
        printSection("2) Entity -- Customer identity is stable even as attributes change");

        Customer customer = new Customer(new CustomerId("C-1"), "Alicia", "alicia@example.com");
        Customer sameCustomerDifferentSnapshot = new Customer(new CustomerId("C-1"), "Alicia T.", "alicia.t@example.com");

        System.out.println("  customer.equals(sameCustomerDifferentSnapshot) = " + customer.equals(sameCustomerDifferentSnapshot));
        assert customer.equals(sameCustomerDifferentSnapshot) : "same identity means same entity, regardless of attributes";

        customer.changeEmail("alicia.new@example.com");
        System.out.println("  Email after change: " + customer.email());
        assert customer.email().equals("alicia.new@example.com");

        try {
            customer.changeEmail("not-an-email");
        } catch (IllegalArgumentException e) {
            System.out.println("  Caught expected exception: " + e.getMessage());
        }
    }

    // -------------------------------------------------------------------------
    // Demo 3: Aggregate Root -- Order enforces invariants across its OrderLine children.
    // -------------------------------------------------------------------------
    private static void demoAggregateRoot() {
        printSection("3) Aggregate Root -- Order enforces invariants (MAX_LINES, DRAFT-only mutation)");

        Order order = new Order("ORD-1", new CustomerId("C-1"));
        order.addLine("SKU-A", 2, new Money(BigDecimal.valueOf(10.00)));
        order.addLine("SKU-B", 1, new Money(BigDecimal.valueOf(25.00)));

        System.out.println("  Order total: " + order.total().amount());
        assert order.total().equals(new Money(BigDecimal.valueOf(45.00)));

        // Exceed MAX_LINES (5) -- the root refuses, protecting the whole aggregate.
        try {
            for (int i = 0; i < 10; i++) order.addLine("SKU-X" + i, 1, Money.zero());
        } catch (IllegalStateException e) {
            System.out.println("  Caught expected exception: " + e.getMessage());
        }

        order.submit();
        System.out.println("  Order status after submit: " + order.status());

        // Cannot mutate a non-DRAFT order -- the root's invariant, not a caller's responsibility to remember.
        try {
            order.addLine("SKU-C", 1, Money.zero());
        } catch (IllegalStateException e) {
            System.out.println("  Caught expected exception: " + e.getMessage());
        }
    }

    // -------------------------------------------------------------------------
    // Demo 4: Repository -- per aggregate root, simple in-memory implementation.
    // -------------------------------------------------------------------------
    private static void demoRepository() {
        printSection("4) Repository -- one repository for the Order aggregate root");

        OrderRepository repository = new InMemoryOrderRepository();

        Order order = new Order("ORD-2", new CustomerId("C-2"));
        order.addLine("SKU-Z", 3, new Money(BigDecimal.valueOf(15.00)));
        repository.save(order);

        Optional<Order> found = repository.findById("ORD-2");
        System.out.println("  Repository found order: " + found.isPresent());
        assert found.isPresent();
        assert found.get().total().equals(new Money(BigDecimal.valueOf(45.00)));

        System.out.println("  Repository lookup for missing id: " + repository.findById("ORD-999").isPresent());
        assert repository.findById("ORD-999").isEmpty();
    }

    // -------------------------------------------------------------------------
    // Demo 5: Domain Event -- OrderSubmitted is raised on submit() and collected,
    // not dispatched immediately -- the application layer publishes it after saving.
    // -------------------------------------------------------------------------
    private static void demoDomainEvent() {
        printSection("5) Domain Event -- OrderSubmitted raised on submit(), collected for later publication");

        OrderRepository repository = new InMemoryOrderRepository();

        Order order = new Order("ORD-3", new CustomerId("C-3"));
        order.addLine("SKU-Q", 1, new Money(BigDecimal.valueOf(99.00)));

        assert order.pullPendingEvents().isEmpty() : "no event should exist before submit()";

        order.submit();
        repository.save(order);   // save FIRST (state durably committed)...

        List<Object> events = order.pullPendingEvents();   // ...THEN collect and "publish" events
        System.out.println("  Events raised by submit(): " + events.size());
        for (Object event : events) {
            if (event instanceof OrderSubmitted submitted) {
                System.out.println("  OrderSubmitted: orderId=" + submitted.orderId()
                        + " total=" + submitted.total().amount() + " occurredAt=" + submitted.occurredAt());
            }
        }
        assert events.size() == 1;
        assert order.pullPendingEvents().isEmpty() : "events must be cleared after being pulled";
    }

    public static void main(String[] args) {
        demoValueObject();
        demoEntity();
        demoAggregateRoot();
        demoRepository();
        demoDomainEvent();

        System.out.println();
        System.out.println("All DDD Tactical Patterns demos completed.");
    }
}
