"""
anomaly_scenarios.py

Injects specific, realistic insider-threat scenarios as "new days" that come
AFTER the normal observation period generated by
user_behavior_baseline_generator.py. These are the days the detector will be
asked to score against each user's personal baseline.

Scenarios injected:
    1. Off-hours login  -- bob_sales (strict 9-5) logs in at 3am.
    2. Data exfiltration -- bob_sales, days before his resignation date,
       downloads ~50x his normal daily volume.
    3. Access-pattern deviation -- dave_engineering (normally only touches
       source_code_repo / engineering_wiki / product_roadmap_docs) suddenly
       accesses exec_board_docs and payroll_db -- systems never touched in
       his baseline history.
    4. Control case (must NOT be flagged) -- carla_nightadmin logs in at her
       usual ~2:30am with a normal download volume and normal systems. This
       proves the detector is personalized, not a blanket "no logins after
       9pm" rule.

Each scenario record has the same shape as a baseline-history day plus a
"label" describing what a human analyst would call it and a "scenario" tag
used later for reporting.
"""

from user_behavior_baseline_generator import USER_PROFILES

# The "new day" index used for every injected scenario (i.e. day 60, the
# first day after a 60-day baseline observation window).
SCENARIO_DAY = 60


def build_scenario_days():
    """
    Returns
    -------
    dict[str, dict]
        user_id -> single "new day" activity record to be scored:
            {"day", "login_hour", "download_mb", "systems_accessed",
             "scenario", "label"}
    """
    scenarios = {}

    # 1 + 2 combined for bob_sales: he is departing soon (resignation date
    # is 5 days after this scenario day) and on this day he BOTH logs in at
    # an unusual hour AND downloads a huge volume of data -- the textbook
    # "bulk download right before departure" pattern.
    bob_profile = USER_PROFILES["bob_sales"]
    scenarios["bob_sales"] = {
        "day": SCENARIO_DAY,
        "login_hour": 3.1,  # strict 9-5 user suddenly logging in at 3am
        "download_mb": round(bob_profile["volume_mean"] * 50, 2),  # ~50x normal volume
        "systems_accessed": ["customer_crm", "sales_pipeline_db"],  # still role-consistent
        "scenario": "offhours_login_and_exfiltration_before_resignation",
        "label": "3am login + ~50x normal download volume, 5 days before resignation date",
        "resignation_in_days": 5,
    }

    # 3. Access-pattern deviation for dave_engineering: normal hour, normal
    # volume, but touches systems completely outside his baseline pool,
    # including highly sensitive ones (exec docs, payroll) far outside an
    # engineer's normal role-based access.
    dave_profile = USER_PROFILES["dave_engineering"]
    scenarios["dave_engineering"] = {
        "day": SCENARIO_DAY,
        "login_hour": round(dave_profile["login_hour_mean"], 2),  # normal hour
        "download_mb": round(dave_profile["volume_mean"], 2),     # normal volume
        "systems_accessed": ["exec_board_docs", "payroll_db", "legal_contracts_share"],
        "scenario": "access_pattern_deviation",
        "label": "Normal hour/volume, but touched systems never seen in baseline "
                  "(exec docs, payroll, legal) -- outside role-based access pattern",
    }

    # 4. Control: carla_nightadmin behaves EXACTLY like her own normal self.
    # This day must NOT be flagged -- it proves personalization, since this
    # same 2:30am login would be a screaming anomaly for a 9-5 user.
    carla_profile = USER_PROFILES["carla_nightadmin"]
    scenarios["carla_nightadmin"] = {
        "day": SCENARIO_DAY,
        "login_hour": round(carla_profile["login_hour_mean"] + 0.1, 2),  # her usual ~2:30am
        "download_mb": round(carla_profile["volume_mean"], 2),           # her usual volume
        "systems_accessed": carla_profile["usual_systems"][:2],          # systems she always uses
        "scenario": "normal_nightshift_activity_control_case",
        "label": "Routine ~2:30am login with normal volume/systems for a night-shift admin "
                 "-- must NOT be flagged",
    }

    return scenarios


if __name__ == "__main__":
    for user_id, day in build_scenario_days().items():
        print(f"{user_id}: {day['label']}")
